// <auto-generated />
using System;
using DevIO.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevIO.Data.Migrations
{
    [DbContext(typeof(YouCatDbContext))]
    [Migration("20211125111314_Identity")]
    partial class Identity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevIO.Business.Models.Estudos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Explicacao")
                        .HasColumnType("varchar(800)");

                    b.Property<int>("NumeroYouCat")
                        .HasColumnType("int");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Resposta")
                        .HasColumnType("varchar(800)");

                    b.HasKey("Id");

                    b.ToTable("Estudos");
                });

            modelBuilder.Entity("DevIO.Business.Models.TipoEstudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("EstudoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EstudoId");

                    b.ToTable("TipoEstudo");
                });

            modelBuilder.Entity("DevIO.Business.Models.TipoEstudo", b =>
                {
                    b.HasOne("DevIO.Business.Models.Estudos", "Estudos")
                        .WithMany("TipoEstudo")
                        .HasForeignKey("EstudoId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
